# This is a basic workflow to help you get started with Actions

name: Build-sphinx-docs

on:
  push:
    # testing on Aryman branch
    branches: [Aryman]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: 
  # This workflow contains a single job called "build"
  build: 
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python 3.10.12
        uses: actions/setup-python@v2
        with:
           python-version: "3.10.12"

      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dicee==0.1.2

      - name: Build HTML and import
        run: |
           sphinx-apidoc -o docs dicee/ && make -C docs/ html && mv docs/_build/html docs/ && ghp-import -n -p -f docs/html